name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t portfolio-anny .

      - name: Stop old container
        run: |
          docker stop portfolio || true

      - name: Remove old container
        run: |
          docker rm portfolio || true

      - name: Start new container
        run: |
          docker run -d \
            --name portfolio \
            -p 192.168.0.150:8080:80 \
            portfolio-anny

      - name: Verify container
        run: |
          docker ps
